# -*- coding: utf-8 -*-
"""Aerofit_case_study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hxqgUqUxCMud3Dr-tEZ8-WMO9yZVjM3K

###### Aerofit is a leading brand in the field of fitness equipment. Aerofit provides a product range including machines such as treadmills, exercise bikes, gym equipment, and fitness accessories to cater to the needs of all categories of people.

# Business Problem:
`Identify the characteristics of the target audience for each type of treadmill offered by the company, to provide a better recommendation of the treadmills to the new customers. `

- investigate whether there are differences across the product with respect to customer characteristics.

1. Descriptive analytics to create a customer profile for each AeroFit treadmill product.
2. For each AeroFit treadmill product, construct two-way contingency tables and compute all conditional and marginal probabilities along with their insights/impact on the business.

# About given Dataset :

- Product Purchased :	KP281, KP481, or KP781
- Age :	In years
- Gender :	Male/Female
- Education :	In years
- MaritalStatus :	Single or partnered
- Usage :	The average number of times the customer plans to use the treadmill each week.
- Income :	Annual income (in USD)
- Fitness :	Self-rated fitness on a 1-to-5 scale, where 1 is the poor shape and 5 is the excellent shape.
- Miles :	The average number of miles the customer expects to walk/run each week

Product Portfolio:

The KP281 is an entry-level treadmill that sells for $1,500.

The KP481 is for mid-level runners that sell for $1,750.

The KP781 treadmill is having advanced features that sell for $2,500.
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib import figure
import warnings
warnings.filterwarnings('ignore')

sns.set(font_scale= 1)

df = pd.read_csv("aerofit_treadmill.txt")

df.shape

df.head(5)

df.tail(5)

df.info()

"""### checking for Null Values in each columns"""

df.isna().sum()

"""No null values found in dataset.

# Pre-Processing Data for Analysis:

#### `Fitness Category`
"""

# Converted fitness rating from Int to Object ! :

df["Fitness_category"] = df["Fitness"]

df["Fitness_category"].value_counts()

df["Fitness_category"].replace({1:"Poor Shape",
                               5:"Excellent Shape",
                               4:"Good Shape",
                               3:"Average Shape",
                               2:"Bad Shape"},inplace=True)

# Product Portfolio:

# The KP281 is an entry-level treadmill that sells for $1,500.
# The KP481 is for mid-level runners that sell for $1,750.
# The KP781 treadmill is having advanced features that sell for $2,500.

"""#### `Merging Price data with original DataSet `"""

product_price = pd.DataFrame({
    "Product":["KP281","KP481","KP781"],
    "Product_price":[1500,1750,2500]

})
product_price

data = df.merge(product_price,on="Product",how = "left")

"""#### `Segmentising Age groups`"""

data["Age_category"] = data["Age"]
data["Age_category"] = pd.cut(data["Age_category"], bins =[0,21,35,45,60], include_lowest=True, labels=["Teen(0-21)","Adult(22-35)","mid_age(36-45)","Towards_old-age(>46)"])
data["Age_category"] = data["Age_category"].astype("object")

"""# `Data Ready for Analysis :`"""

data

"""### describing categorical features : :"""

data.describe(include="object").T

"""### Describing numeric Data :"""

data.describe()

"""###  `from above information`
1. The median age of customers is 26 years.
2. Most users are adults between 22 and 35 years old, with a predominance of males who are married.
3. The best-selling product is KP281.
4. The majority of customers have a fitness level above average (>3 according to the given data).
5. The median distance run/walked per customer is 94 miles.

#### `Additional information from data :`

1. The median income of customers is $50,596.5 USD.
2. The median average usage per customer is 3 days a week.
3. The average customer education level is between 15 and 16 years.
"""

d = data[["Age","Education","Fitness","Income","Miles","Gender"]]

x = sns.pairplot(d,
                kind = "reg",
                hue="Gender")
x.map_diag(sns.kdeplot)
plt.show()

"""### Distribution of all numerical features : and check for outliers :

"""

d = data[["Age","Education","Usage","Fitness","Income","Miles","Gender"]]

"""#### Distribution of Miles run by customer in given Data"""

sns.boxplot(x = "Miles",data = d,y="Gender")
plt.show()

IQR = np.percentile(data["Miles"],75)  -   np.percentile(data["Miles"],25)
Q3 = np.percentile(data["Miles"],75)
Q1 = np.percentile(data["Miles"],25)
UpperWhisker = Q3 + (1.5*(IQR))
UpperWhisker

Q1

Q3

IQR

outlier_data = data[data["Miles"]>UpperWhisker]
print("Outliers : ",len(outlier_data))

"""#### Insights from Customers who run more than 187.875 (outliers)."""

outlier_data["Product"].value_counts()

outlier_data["Fitness_category"].value_counts()

"""13 outlier in column "Miles".
Customers who fall in outliers as per their miles run/walk , uses product KP781 and are in excellent shape.



"""

plt.figure(figsize=(5,4))
sns.distplot(data["Miles"])
plt.show()

sns.boxplot(x = "Income",data = d,y="Gender")
plt.show()

IQR = np.percentile(data["Income"],75)-np.percentile(data["Income"],25)
Q3 = np.percentile(data["Income"],75)
Q1 = np.percentile(data["Income"],25)
UpperWhisker = Q3 + (1.5*(IQR))
UpperWhisker

(data["Income"] > UpperWhisker).value_counts()

"""##### 19 customers who's spending capacity is way more than most of the customers

# General Sales Analysis  :
"""

data["Gender"].value_counts()

sns.countplot(x = "Gender" , data = data)
plt.title("Count of Customers Gender wice")

plt.xlabel("Gender")
plt.ylabel("Number of Customers")
plt.show()

"""### Quantity per Product Sold"""

data["Product"].value_counts(normalize=True)*100

sns.barplot(x = data["Product"].value_counts().index,
           y = data["Product"].value_counts())
plt.title("Product : Number of Product Sold")

plt.xlabel("Products")
plt.ylabel("Number of Product Sold")
plt.show()

data.groupby("Product")["Product_price"].sum()

sns.barplot(x = data.groupby("Product")["Product_price"].sum().index,
           y = data.groupby("Product")["Product_price"].sum())

plt.ylabel("Revenue Per Product")

"""#### The analysis highlights KP281 as the top-selling product, with a revenue of $120,000 USD, indicating its strong performance in sales.

#### KP481 and KP781 also contribute significantly to the revenue, each generating around $100,000 USD, showcasing their importance in the product lineup.

#### These figures underscore the diverse revenue streams from different products, emphasizing the need for a balanced product portfolio.

## Two-Way Contingency Table :

## `Across gender`
"""

sns.countplot(x = "Product", data= data, hue = "Gender")
plt.xlabel("Products")
plt.title("Count of Male and Female uses Particular Products")
plt.show()

pd.crosstab([data["Product"]],data["Gender"],margins=True)

((pd.crosstab(data["Product"],data["Gender"],margins=True))/180)*100

"""#### Marginal Probability:
1. The probability of a male customer purchasing any product is 57.77%.
2. The probability of a female customer purchasing any product is 42.22%.
#### Marginal Probability of Any Customer Buying:
1. For product KP281 (cheapest/entry-level product), the probability is 44.44%.
2. For product KP481 (for intermediate users), the probability is 33.33%.
3. For product KP781 (product for extensive use by those who run/walk more miles), the probability is 22.22%.

### Conditional Probabilities :
"""

(pd.crosstab([data["Product"]],data["Gender"],margins=True,normalize="columns"))*100

"""#### The analysis of probabilities for users of KP281, KP481, and KP781, given their gender, reveals interesting trends:

1. Probability of female customers purchasing KP281 is higher (52.63%) compared to male customers (38.46%), indicating that KP281 is more recommended for female customers.
2. KP781 has a higher probability of being purchased by male customers (31.73%) compared to female customers (9.21%), suggesting that KP781 is more appealing to male customers.
3. For KP481, the probability of purchase is higher for female customers (38.15%) compared to male customers (29.80%), indicating that KP481 is specifically recommended for female customers who are intermediate users.

## `Across Marital Status`
"""

data["MaritalStatus"].value_counts(normalize=True)*100

sns.countplot(x = "Product", data= data, hue = "MaritalStatus")
plt.xlabel("Products")
plt.title("Count of Male and Female uses Particular Products")
plt.show()

pd.crosstab([data["Product"]],data["MaritalStatus"],margins=True)

(pd.crosstab([data["Product"]],data["MaritalStatus"],margins=True)/180)*100

"""
Marginal Probability for
- Married Customers : 59.44 %
- Single Customers : 40.555 %
    
"""

pd.crosstab([data["Product"]],data["MaritalStatus"],margins=True,normalize="columns")*100

"""#### The analysis of probabilities for users of KP281, KP481, and KP781, based on their relationship status, reveals the following insights:

1. Probability of a partnered (married or in a relationship) person purchasing any product is 59.44%, while the probability for a single person is 40.55%.
2. For KP281 and KP481, the probability of purchase is slightly higher for partnered individuals (KP281: 44.85%, KP481: 33.64%) compared to single individuals (KP281: 43.83%, KP481: 32.87%).
3. For KP781, the probability of purchase is higher for single individuals (23.28%) compared to partnered individuals (21.49%).
4. Therefore, KP781 is also recommended for single individuals who are more active in exercising.

# Product - Gender - Mile
"""

sns.catplot(x= "Product", y = "Miles",hue="Gender" ,kind = "box", data= data,height=7, aspect=8/11 )
plt.xticks(rotation = 0)
plt.show()

"""KP481 is ideal for males looking to run or walk 60-130 miles weekly, making it a versatile product for intermediate users."""

np.round(pd.crosstab([data["Product"]],data["Gender"],values=data["Miles"],aggfunc=np.mean,margins=True),2)

"""#### Observations and Insights:
1. Female customers engaging in extensive exercise, averaging 180 miles, predominantly use product KP781, surpassing the average use by male customers.
2. KP781 is recommended for female customers engaged in extensive exercise.
3. Male customers engaging in moderate exercise, averaging 90 miles, favor product KP281.
4. Both male and female customers engaging in moderate exercise, averaging 87-88 miles, favor product KP481.

### Overall Picture over  Few categorical and Numerical features :
"""

plt.figure(figsize=(10,10))

sns.scatterplot(x = "Miles",y="Income",data = data, hue= "Fitness",style="Gender")

"""- Above scattered Plot shows the overall picture over customer's income, how much they exercise (run/walk miles) given their gender and their fitness level.
- Most of the customer's fitness level is around 3 to 4 . and it says people who run more miles are having good fitness level.
- Though there is a trend with income and miles. But there are very few customers who earn a lot and run more miles.

## `Product | Miles - Fitness `
"""

sns.catplot(x= "Fitness_category", y = "Miles" ,kind = "box",hue="Product", data= data.sort_values(by="Fitness"),height=10, aspect=8/11)
plt.xticks(rotation = 90)
plt.show()

"""## `Product - Miles `

`People who run/walk more miles(>130) , are more likely to use product KP781! `

`People who walk/run around 60 to 130 miles are more likely to use KP281 and KP481 products.`
"""

sns.catplot(x= "Product", y = "Miles" ,kind = "box", data= data,height=8, aspect=8/11)
plt.xticks(rotation = 0)
plt.show()

"""`Customers who walk/run 70-90 miles, are using KP281 `

`Customers who walk/run 70-130 or more miles are using KP481.`

`Customers who walk/run 120 to 200 or more miles uses KP781.`
"""

sns.catplot(x= "Product", y = "Usage" ,kind = "box", data= data,height=8, aspect=8/11)
plt.xticks(rotation = 0)
plt.show()

"""`Customers who uses Treadmill 4 to 6 days a week  , are more likely to use KP781 .`

`Customers who uses Treadmill 3 to 4 days a week  , are more likely to use KP481 .`

`Customers who uses Treadmill 3 to 4 days a week  , are more likely to use KP281 .`

## `Correlation Between Income and Product Price : `

#### Observations and Insights:
1. The plot indicates a positive trend: individuals with higher incomes are more likely to purchase more expensive products.
2. Customers in excellent and good physical shape are more inclined to spend more and purchase costlier, more reliable products suited for extensive use.
"""

sns.jointplot(x = data["Product_price"],
              y= data["Income"],
             height=5, kind="scatter",hue=data["Fitness_category"])

sns.regplot(x = data["Product_price"],
              y= data["Income"],)

"""### Relashion of Miles and FitnessLevel"""

sns.jointplot(x = data["Fitness"],
              y= data["Miles"],
             height=6, kind="reg") # ['scatter', 'hist', 'hex', 'kde', 'reg', 'resid'],

"""## `Correlation between Income and miles :`"""

sns.jointplot(x = data["Income"],
              y= data["Miles"],
             height=6, kind="reg") # ['scatter', 'hist', 'hex', 'kde', 'reg', 'resid'],

sns.jointplot(x = data["Income"],
              y= data["Miles"],
             height=6, kind="kde") # ['scatter', 'hist', 'hex', 'kde', 'reg', 'resid'],

"""#### Observations and Insights:

- Majority customer base has earning from 25,000 to 75,000USD
- and prefer to exercises very less to 175 miles a week.

# Customer Age
"""

sns.boxplot(x = "Age",data = d,y="Gender")
plt.show()

plt.figure(figsize=(5,4))
sns.distplot(data["Age"])
plt.show()

"""### Age category of customers per Product :"""

data.loc[data["Product"]=="KP281"]["Age_category"].value_counts()

data.loc[data["Product"]=="KP481"]["Age_category"].value_counts()

data.loc[data["Product"]=="KP781"]["Age_category"].value_counts()

pd.crosstab(index=data["Product"],columns=data["Age_category"], margins=True)

np.round((pd.crosstab(index=data["Product"],columns=data["Age_category"],normalize="columns", margins=True))*100,2)

np.round((pd.crosstab(index=data["Product"],columns=data["Age_category"], margins=True)),2)

data.groupby("Age_category")["Product"].count()

"""#### Observations and Insights:
1. The majority of the customer base falls into the Adult (22-35) age category, with 135 customers.
2. There are 17 customers in the Teen age category and 22 customers in the mid-age category.
3. Probability of Teenage Customers buying KP281 is 58.82%, and for KP481 is 41.18%.
4. For Adults, the probability of buying KP281 is 41.48%, for KP481 is 33.33%, and for KP781 is 25.19%.
5. The probability of customers above the age of 46 buying KP281 is 50%, for KP481 is 16.67%, and for KP781 is 33.33%.
6. For customers in the mid-age group (36-45 years), the probability of buying KP281 is 50%, for KP481 is 31.82%, and for KP781 is 18.18%.

# Fitness category
"""

pd.crosstab(columns=data["Fitness_category"],index=data["Product"],margins=True)

np.round(pd.crosstab(index=data["Product"],columns=data["Fitness_category"],normalize="columns")*100,2)

"""if the person is in excellent shape , the probabiliy that he is using KP781 is more than 90 %.

### Customer Profiling - Categorization of Users
#### KP281:
- Product Type: Entry-level and most affordable, with maximum sales.
- Gender Distribution: Equally popular among both male and female customers.
- Usage Frequency: Customers use this product 3 to 4 times a week.
- Fitness Level: Users are typically in average shape.
- Miles Run/Walk: Customers walk/run an average of 70 to 90 miles per week.
- Age Group: More general purpose, suitable for all age groups and fitness levels.
#### KP481:
- Product Type: Intermediate price range.
- Fitness Level: Users' fitness level varies from bad to average shape.
- Miles Run/Walk: Customers prefer this model to run more miles per week (70 to 130 or more).
- Gender Preference: Higher probability of selling to female customers.
- Age Group: Customers are from adult, teen, and mid-age categories.
#### KP781:
- Product Type: Highest price and least sold product.
- Fitness Level: Preferred by customers who exercise more extensively and run more miles.
- Miles Run/Walk: Customers walk/run an average of 120 to 200 or more miles per week.
- Usage Frequency: Users use this product 4 to 5 times a week at least.
- Fitness Level: If a person is in excellent shape, the probability of using KP781 is more than 90%.
- Gender Preference: More popular among male customers.
- Age Group: Most users are old people above 45 years and adults.

# `Recommendations  : `

- Recommendation for KP781: Target users who exercise/run more frequently, cover more miles, and have higher income. Since KP781 is the least selling product (22.2% share), consider recommending it to customers who already exercise at an intermediate to extensive level, especially if they are considering KP481. Targeted age categories are adults and those above 45.
- Recommendation for KP481: Specifically target female customers who walk/run more miles, as the data shows a higher probability for them to purchase KP481. The statistical summary for fitness level and miles for KP481 is not as good as KP281, which is a cheaper product. This difference might be due to the price, as customers prefer to purchase KP281. Consider making necessary changes to KP481 to enhance the customer experience and increase sales.

# Some necessary exploration on Cross Tabs :
"""

pd.crosstab(index=[data["Product"],data["Fitness_category"]],columns=data["Gender"])

pd.crosstab(index=[data["Product"],data["Fitness_category"]],columns=data["Gender"],normalize="index")*100

data[data["Miles"]>150]["Fitness_category"].value_counts()

data[data["Miles"]>np.percentile(data["Miles"],90)]["Fitness_category"].value_counts()

pd.crosstab(index=[data["Product"],data["MaritalStatus"]],columns=data["Gender"],margins=True)



